import re
import logging

logger = logging.getLogger("pipeline.danmaku_post")

# Styles whose events are subject to display-area clipping
_CLIPPABLE_STYLES = {"R2L"}

# Styles whose PrimaryColour alpha is adjusted by opacity setting
_OPACITY_STYLES = {"R2L", "L2R", "TOP", "BTM"}

# Regex to extract Y coordinate from \move(x1,y1,x2,y2)
_MOVE_RE = re.compile(r"\\move\(\s*[-\d.]+\s*,\s*([-\d.]+)\s*,")

# Regex to match \c&HBBGGRR color override tags (with surrounding braces handled separately)
_COLOR_TAG_RE = re.compile(r"\{\\c&H[0-9A-Fa-f]{6,8}\}")

# Regex to match PrimaryColour in a style definition: &HAA... (2-digit alpha + 6-digit color)
_PRIMARY_COLOUR_RE = re.compile(r"&H([0-9A-Fa-f]{2})([0-9A-Fa-f]{6})")


def postprocess_ass(ass_file, resolution_y, display_area=1.0, opacity=0.8, color_enabled=True):
    """Post-process an ASS file generated by dmconvert.

    Args:
        ass_file: Path to the ASS file (modified in-place).
        resolution_y: Video vertical resolution in pixels.
        display_area: 0.0-1.0, fraction of screen from top for scrolling danmaku.
        opacity: 0.0-1.0, danmaku opacity (1.0 = fully opaque).
        color_enabled: If False, strip all \\c color override tags from events.
    """
    with open(ass_file, "r", encoding="utf-8-sig") as f:
        content = f.read()

    lines = content.splitlines()
    result = []
    section = None
    removed_count = 0

    y_threshold = resolution_y * display_area

    for line in lines:
        stripped = line.strip()

        # Track which section we're in
        if stripped.startswith("["):
            section = stripped

        # --- Style opacity adjustment ---
        if section == "[V4+ Styles]" and stripped.startswith("Style:"):
            line = _adjust_style_opacity(line, opacity)

        # --- Event processing ---
        if section == "[Events]" and stripped.startswith("Dialogue:"):
            style = _extract_style(stripped)

            # Display area clipping for scrolling danmaku
            if style in _CLIPPABLE_STYLES and display_area < 1.0:
                y = _extract_move_y(stripped)
                if y is not None and y > y_threshold:
                    removed_count += 1
                    continue

            # Color tag removal
            if not color_enabled:
                line = _remove_color_tags(line)

        result.append(line)

    with open(ass_file, "w", encoding="utf-8-sig") as f:
        f.write("\n".join(result))

    if removed_count > 0:
        logger.info(f"弹幕后处理：移除了 {removed_count} 条超出显示区域的滚动弹幕")


def _extract_style(dialogue_line):
    """Extract the style name from a Dialogue line.

    Format: Dialogue: layer,start,end,Style,Name,...
    """
    # Split on commas; style is the 4th field (index 3)
    parts = dialogue_line.split(",", 5)
    if len(parts) >= 4:
        return parts[3].strip()
    return ""


def _extract_move_y(dialogue_line):
    """Extract the Y coordinate from \\move(x1,y,x2,y) in a Dialogue line."""
    m = _MOVE_RE.search(dialogue_line)
    if m:
        try:
            return float(m.group(1))
        except ValueError:
            return None
    return None


def _adjust_style_opacity(style_line, opacity):
    """Adjust the PrimaryColour alpha channel for eligible styles."""
    # Parse style name (first field after "Style:")
    after_style = style_line.split("Style:", 1)
    if len(after_style) < 2:
        return style_line

    fields = after_style[1].split(",")
    if len(fields) < 4:
        return style_line

    style_name = fields[0].strip()
    if style_name not in _OPACITY_STYLES:
        return style_line

    # Compute new alpha: ASS alpha is inverted (00=opaque, FF=transparent)
    new_alpha = format(round((1.0 - opacity) * 255), "02X")

    # Replace alpha in PrimaryColour (4th field, index 3)
    fields[3] = _PRIMARY_COLOUR_RE.sub(
        lambda m: f"&H{new_alpha}{m.group(2)}", fields[3]
    )

    return style_line.split("Style:", 1)[0] + "Style:" + ",".join(fields)


def _remove_color_tags(line):
    """Remove all {\\c&HBBGGRR} color override tags from a line."""
    return _COLOR_TAG_RE.sub("", line)
